services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: medicare
      MYSQL_USER: medicare
      MYSQL_PASSWORD: medicare
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql