version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: medicare
      MYSQL_USER: medicare
      MYSQL_PASSWORD: medicare
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
  tomcat:
    image: bitnami/tomcat:latest
    container_name: tomcat
    environment:
      TOMCAT_USERNAME: medicare
      TOMCAT_PASSWORD: medicare
    ports:
      - "8080:8080"
  nginx:
    build: .
    container_name: nginx
    environment:
      USER: medicare
      PASSWORD: medicare
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - ./medicareFE:/data
      - ./sshkeys:/etc/ssh/keys
